export const FETCH_API_USER = 'FETCH_API_USER';
export const FETCH_API_PRODUCT = 'FETCH_API_PRODUCT';
export const VIEW_DETAIL_PRODUCT = 'VIEW_DETAIL_PRODUCT';

// LOGIN
export const LOGIN_PROGRESS = "LOGIN_PROGRESS";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//REGISTER
export const REGISTER_PROGRESS = "REGISTER_PROGRESS";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_LIKE = 'REGISTER_LIKE';

//REGISTER
export const PRODUCT_FAILED = "PRODUCT_FAILED";
export const PRODUCT_CREATE = 'PRODUCT_CREATE';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';